// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcZkXla0gB-rlO4g-WIOX8nXWzzbxzwfw',
    appId: '1:153212939540:web:c0173f83b7adff9bf56601',
    messagingSenderId: '153212939540',
    projectId: 'moooood',
    authDomain: 'moooood.firebaseapp.com',
    storageBucket: 'moooood.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl4X_zf0e0uuj1fvj4eA2nVryQYQyoPFc',
    appId: '1:153212939540:android:5b2c931109764260f56601',
    messagingSenderId: '153212939540',
    projectId: 'moooood',
    storageBucket: 'moooood.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZKhpRfwbgFrV9Eh0q42VGPb_WOxQpA_Y',
    appId: '1:153212939540:ios:25a88e705a4029edf56601',
    messagingSenderId: '153212939540',
    projectId: 'moooood',
    storageBucket: 'moooood.appspot.com',
    iosBundleId: 'kr.raom.moodTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZKhpRfwbgFrV9Eh0q42VGPb_WOxQpA_Y',
    appId: '1:153212939540:ios:a0eb57173ae0ecd4f56601',
    messagingSenderId: '153212939540',
    projectId: 'moooood',
    storageBucket: 'moooood.appspot.com',
    iosBundleId: 'com.example.moodTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcZkXla0gB-rlO4g-WIOX8nXWzzbxzwfw',
    appId: '1:153212939540:web:dc7eb1db4456e840f56601',
    messagingSenderId: '153212939540',
    projectId: 'moooood',
    authDomain: 'moooood.firebaseapp.com',
    storageBucket: 'moooood.appspot.com',
  );

}